apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-global
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zenmyx@gmail.com
    privateKeySecretRef:
      name: letsencrypt-global
    solvers:
    - selector:
        dnsZones:
          - "domain.com"
      dns01:
        route53:
          region: eu-central-1
          hostedZoneID: ABCDEXAMPLE
          accessKeyID: ABCDEXAMPLE
          secretAccessKeySecretRef:
            name: aws-route53-creds
            key: password.txt
